config/routes.rb
Rails.application.routes.draw do
  resources :product_modules
  resources :invoices
  resources :fees
  resources :adjustments
  resources :module_types
  resources :fee_types
  resources :services
  resources :contacts
  resources :quotes
  resources :agreements
  resources :agreement_types
  resources :pos
  resources :kms_versions
  resources :customers
  resources :posts
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :quote
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :agreement_type
end

app/models/agreement_type.rb
class AgreementType < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :kms_version
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :quote
  belongs_to :fee_type
end

app/models/fee_type.rb
class FeeType < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :po
end

app/models/kms_version.rb
class KmsVersion < ApplicationRecord
end

app/models/module_type.rb
class ModuleType < ApplicationRecord
end

app/models/po.rb
class Po < ApplicationRecord
  belongs_to :customer
  belongs_to :quote
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/product_module.rb
class ProductModule < ApplicationRecord
  belongs_to :customer
  belongs_to :po
  belongs_to :module_type
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :quote
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/quotes_controller.rb
class QuotesController < InheritedResources::Base

  private

    def quote_params
      params.require(:quote).permit(:customer_id_id, :quote_number, :quote_date, :valid_to, :total)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/p_os_helper.rb
module POsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/quotes/_form.html.erb
<%= form_for(quote) do |f| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id_id %>
    <%= f.text_field :customer_id_id %>
  </div>

  <div class="field">
    <%= f.label :quote_number %>
    <%= f.text_field :quote_number %>
  </div>

  <div class="field">
    <%= f.label :quote_date %>
    <%= f.date_select :quote_date %>
  </div>

  <div class="field">
    <%= f.label :valid_to %>
    <%= f.date_select :valid_to %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Quote number</th>
      <th>Quote date</th>
      <th>Valid to</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer_id %></td>
        <td><%= quote.quote_number %></td>
        <td><%= quote.quote_date %></td>
        <td><%= quote.valid_to %></td>
        <td><%= quote.total %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer_id %>
</p>

<p>
  <strong>Quote number:</strong>
  <%= @quote.quote_number %>
</p>

<p>
  <strong>Quote date:</strong>
  <%= @quote.quote_date %>
</p>

<p>
  <strong>Valid to:</strong>
  <%= @quote.valid_to %>
</p>

<p>
  <strong>Total:</strong>
  <%= @quote.total %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>