config/routes.rb
Rails.application.routes.draw do
  resources :product_modules
  resources :invoices
  resources :fees
  resources :adjustments
  resources :module_types
  resources :fee_types
  resources :services
  resources :contacts
  resources :quotes
  resources :agreements
  resources :agreement_types
  resources :pos
  resources :kms_versions
  resources :customers
  resources :posts
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :quote
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :agreement_type
end

app/models/agreement_type.rb
class AgreementType < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :kms_version
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :quote
  belongs_to :fee_type
end

app/models/fee_type.rb
class FeeType < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :po
end

app/models/kms_version.rb
class KmsVersion < ApplicationRecord
end

app/models/module_type.rb
class ModuleType < ApplicationRecord
end

app/models/po.rb
class Po < ApplicationRecord
  belongs_to :customer
  belongs_to :quote
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :quote
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/kms_versions_controller.rb
class KmsVersionsController < InheritedResources::Base

  private

    def kms_version_params
      params.require(:kms_version).permit(:version)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/kms_versions_helper.rb
module KmsVersionsHelper
end

app/helpers/p_os_helper.rb
module POsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kms_versions/_form.html.erb
<%= form_for(kms_version) do |f| %>
  <% if kms_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kms_version.errors.count, "error") %> prohibited this kms_version from being saved:</h2>

      <ul>
      <% kms_version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :version %>
    <%= f.text_field :version %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kms_versions/edit.html.erb
<h1>Editing Kms Version</h1>

<%= render 'form', kms_version: @kms_version %>

<%= link_to 'Show', @kms_version %> |
<%= link_to 'Back', kms_versions_path %>

app/views/kms_versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kms Versions</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kms_versions.each do |kms_version| %>
      <tr>
        <td><%= kms_version.version %></td>
        <td><%= link_to 'Show', kms_version %></td>
        <td><%= link_to 'Edit', edit_kms_version_path(kms_version) %></td>
        <td><%= link_to 'Destroy', kms_version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kms Version', new_kms_version_path %>

app/views/kms_versions/new.html.erb
<h1>New Kms Version</h1>

<%= render 'form', kms_version: @kms_version %>

<%= link_to 'Back', kms_versions_path %>

app/views/kms_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @kms_version.version %>
</p>

<%= link_to 'Edit', edit_kms_version_path(@kms_version) %> |
<%= link_to 'Back', kms_versions_path %>