config/routes.rb
Rails.application.routes.draw do
  resources :product_modules
  resources :invoices
  resources :fees
  resources :adjustments
  resources :module_types
  resources :fee_types
  resources :services
  resources :contacts
  resources :quotes
  resources :agreements
  resources :agreement_types
  resources :pos
  resources :kms_versions
  resources :customers
  resources :posts
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :quote
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :agreement_type
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :kms_version
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :quote
  belongs_to :fee_type
end

app/models/fee_type.rb
class FeeType < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :po
end

app/models/kms_version.rb
class KmsVersion < ApplicationRecord
end

app/models/module_type.rb
class ModuleType < ApplicationRecord
end

app/models/po.rb
class Po < ApplicationRecord
  belongs_to :customer
  belongs_to :quote
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/product_module.rb
class ProductModule < ApplicationRecord
  belongs_to :customer
  belongs_to :po
  belongs_to :module_type
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :quote
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/product_modules_controller.rb
class ProductModulesController < InheritedResources::Base

  private

    def product_module_params
      params.require(:product_module).permit(:module_type_id, :customer_id_id, :po_number_id)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/p_os_helper.rb
module POsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/product_modules_helper.rb
module ProductModulesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_modules/_form.html.erb
<%= form_for(product_module) do |f| %>
  <% if product_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_module.errors.count, "error") %> prohibited this product_module from being saved:</h2>

      <ul>
      <% product_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :module_name %>
    <%= f.text_area :module_name %>
  </div>

  <div class="field">
    <%= f.label :customer_id_id %>
    <%= f.text_field :customer_id_id %>
  </div>

  <div class="field">
    <%= f.label :po_number_id %>
    <%= f.text_field :po_number_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_modules/edit.html.erb
<h1>Editing Product Module</h1>

<%= render 'form', product_module: @product_module %>

<%= link_to 'Show', @product_module %> |
<%= link_to 'Back', product_modules_path %>

app/views/product_modules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Modules</h1>

<table>
  <thead>
    <tr>
      <th>Module name</th>
      <th>Customer</th>
      <th>Po number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_modules.each do |product_module| %>
      <tr>
        <td><%= product_module.module_name %></td>
        <td><%= product_module.customer_id %></td>
        <td><%= product_module.po_number %></td>
        <td><%= link_to 'Show', product_module %></td>
        <td><%= link_to 'Edit', edit_product_module_path(product_module) %></td>
        <td><%= link_to 'Destroy', product_module, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Module', new_product_module_path %>

app/views/product_modules/new.html.erb
<h1>New Product Module</h1>

<%= render 'form', product_module: @product_module %>

<%= link_to 'Back', product_modules_path %>

app/views/product_modules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Module name:</strong>
  <%= @product_module.module_name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @product_module.customer_id %>
</p>

<p>
  <strong>Po number:</strong>
  <%= @product_module.po_number %>
</p>

<%= link_to 'Edit', edit_product_module_path(@product_module) %> |
<%= link_to 'Back', product_modules_path %>