config/routes.rb
Rails.application.routes.draw do
  resources :product_modules
  resources :invoices
  resources :fees
  resources :adjustments
  resources :module_types
  resources :fee_types
  resources :services
  resources :contacts
  resources :quotes
  resources :agreements
  resources :agreement_types
  resources :pos
  resources :kms_versions
  resources :customers
  resources :posts
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'admin/dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :quote
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :agreement_type
end

app/models/agreement_type.rb
class AgreementType < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :kms_version
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :quote
  belongs_to :fee_type
end

app/models/fee_type.rb
class FeeType < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :po
end

app/models/kms_version.rb
class KmsVersion < ApplicationRecord
end

app/models/module_type.rb
class ModuleType < ApplicationRecord
end

app/models/po.rb
class Po < ApplicationRecord
  belongs_to :customer
  belongs_to :quote
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/product_module.rb
class ProductModule < ApplicationRecord
  belongs_to :customer
  belongs_to :po
  belongs_to :module_type
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :quote
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/fees_controller.rb
class FeesController < InheritedResources::Base

  private

    def fee_params
      params.require(:fee).permit(:quote_id, :fee_type_id, :price)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/p_os_helper.rb
module POsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fees/_form.html.erb
<%= form_for(fee) do |f| %>
  <% if fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
      <% fee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_id %>
    <%= f.text_field :quote_id %>
  </div>

  <div class="field">
    <%= f.label :fee_type_id %>
    <%= f.text_field :fee_type_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fees</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Fee type</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.quote_id %></td>
        <td><%= fee.fee_type %></td>
        <td><%= fee.price %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @fee.quote %>
</p>

<p>
  <strong>Fee type:</strong>
  <%= @fee.fee_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fee.price %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>